---
# handlers file for RHEL8-CIS

- name: sysctl flush ipv4 route table
  become: yes
  sysctl:
      name: net.ipv4.route.flush
      value: 1
      sysctl_set: yes
  when: ansible_virtualization_type != "docker"

- name: sysctl flush ipv6 route table
  become: yes
  sysctl:
      name: net.ipv6.route.flush
      value: 1
      sysctl_set: yes
  when: ansible_virtualization_type != "docker"
  ignore_errors: yes

- name: systemd restart tmp.mount
  become: yes
  systemd:
      name: tmp.mount
      daemon_reload: yes
      enabled: yes
      masked: no
      state: reloaded

- name: systemd restart var-tmp.mount
  become: yes
  systemd:
      name: var-tmp.mount
      daemon_reload: yes
      enabled: yes
      masked: no
      state: reloaded

- name: generate new grub config
  become: yes
  command: grub2-mkconfig -o "{{ grub_cfg.stat.lnk_source }}"

- name: restart firewalld
  become: yes
  service:
      name: firewalld
      state: restarted

- name: restart xinetd
  become: yes
  service:
      name: xinetd
      state: restarted

- name: restart sshd
  become: yes
  service:
      name: sshd
      state: restarted

- name: reload dconf
  become: yes
  command: dconf update

- name: restart auditd
  command: /sbin/service auditd restart
  changed_when: no
  check_mode: no
  failed_when: no
  args:
      warn: no
  when:
      - not rhel8cis_skip_for_travis
  tags:
      - skip_ansible_lint

- name: grub2cfg to /boot/grub2/grub.cfg
  shell: |
    /sbin/grub2-mkconfig -o /boot/grub2/grub.cfg
    test -f /boot/grub2/grub.cfg && chown root:root /boot/grub2/grub.cfg
    test -f /boot/grub2/grub.cfg && chmod u-x /boot/grub2/grub.cfg
    test -f /boot/grub2/grub.cfg && chmod og-rwx /boot/grub2/grub.cfg
    test -f /boot/grub2/grubenv && chown root:root /boot/grub2/grubenv
    test -f /boot/grub2/grubenv && chmod u-x /boot/grub2/grubenv
    test -f /boot/grub2/grubenv && chmod og-rwx /boot/grub2/grubenv
    test -f /boot/grub2/user.cfg && chown root:root /boot/grub2/user.cfg
    test -f /boot/grub2/user.cfg && chmod u-x /boot/grub2/user.cfg
    test -f /boot/grub2/user.cfg && chmod og-rwx /boot/grub2/user.cfg
  ignore_errors: True
  listen: grub2cfg

- name: grub2cfg to /boot/efi/EFI/redhat/grub.cfg
  shell: |
    test -f /boot/efi/EFI/redhat/grub.cfg && /sbin/grub2-mkconfig -o /boot/efi/EFI/redhat/grub.cfg
    test -f /boot/efi/EFI/redhat/grub.cfg && chown root:root /boot/efi/EFI/redhat/grub.cfg
    test -f /boot/efi/EFI/redhat/grub.cfg && chmod og-rwx /boot/efi/EFI/redhat/grub.cfg
    test -f /boot/efi/EFI/redhat/user.cfg && chown root:root /boot/efi/EFI/redhat/user.cfg
    test -f /boot/efi/EFI/redhat/user.cfg && chmod u-x /boot/efi/EFI/redhat/user.cfg
    test -f /boot/efi/EFI/redhat/user.cfg && chmod og-rwx /boot/efi/EFI/redhat/user.cfg
  ignore_errors: True
  listen: grub2cfg

- name: authselect apply-changes
  command: "authselect apply-changes"

